import type { BuildDef, BuildId, HouseTier, RegionId, Res } from './types';

export const SIZE = 28;
export const START_R = 5;
export const TAX_MS = 18_000;
export const SAVE = 'metrobuilder-full-v3';
export const WEEK_MS = 10 * 60_000;

export const RES: Record<Res, { name: string; icon: string; sell: number }> = {
  wood: { name: 'Holz', icon: '🪵', sell: 2 },
  metal: { name: 'Metall', icon: '⚙️', sell: 3 },
  plastic: { name: 'Kunststoff', icon: '🧪', sell: 3 },
  glass: { name: 'Glas', icon: '🪟', sell: 4 },
  chemicals: { name: 'Chemikalien', icon: '🧴', sell: 4 },
  planks: { name: 'Bretter', icon: '📦', sell: 8 },
  tools: { name: 'Werkzeug', icon: '🔧', sell: 12 },
  furniture: { name: 'Möbel', icon: '🪑', sell: 18 },
  fabric: { name: 'Stoffe', icon: '🧵', sell: 10 },
};

export const REGIONS: Record<
  RegionId,
  { name: string; icon: string; terrain: 'grass' | 'sand' | 'snow'; blurb: string; unlockCost: number }
> = {
  valley: {
    name: 'Tal',
    icon: '🌿',
    terrain: 'grass',
    blurb: 'Startregion — ausgewogen.',
    unlockCost: 0,
  },
  desert: {
    name: 'Wüste',
    icon: '🏜️',
    terrain: 'sand',
    blurb: 'Mehr Metall, weniger Wasser.',
    unlockCost: 500,
  },
  coast: {
    name: 'Küste',
    icon: '🌊',
    terrain: 'grass',
    blurb: 'Glas & Handel-Bonus.',
    unlockCost: 800,
  },
  snow: {
    name: 'Schnee',
    icon: '❄️',
    terrain: 'snow',
    blurb: 'Energie teurer, Prestige-Bonus.',
    unlockCost: 1200,
  },
};

export const HOUSE: HouseTier[] = [
  { level: 1, name: 'Hütte', pop: 4, tax: 10, cost: 40, needs: {} },
  { level: 2, name: 'Haus', pop: 12, tax: 28, cost: 110, needs: { planks: 3, tools: 1 } },
  {
    level: 3,
    name: 'Villa',
    pop: 26,
    tax: 65,
    cost: 320,
    needs: { planks: 5, furniture: 2, fabric: 2, glass: 2 },
  },
  {
    level: 4,
    name: 'Turm',
    pop: 55,
    tax: 150,
    cost: 900,
    needs: { furniture: 5, tools: 4, fabric: 4, glass: 4, plastic: 3 },
    needSchool: true,
  },
  {
    level: 5,
    name: 'Hochhaus',
    pop: 95,
    tax: 280,
    cost: 2200,
    needs: { furniture: 8, tools: 7, fabric: 6, glass: 6, plastic: 5, chemicals: 3 },
    needSchool: true,
  },
  {
    level: 6,
    name: 'Wolkenkratzer',
    pop: 160,
    tax: 480,
    cost: 5500,
    needs: { furniture: 14, tools: 12, fabric: 10, glass: 12, plastic: 10, chemicals: 6 },
    needSchool: true,
  },
];

export const DEFS: Record<BuildId, BuildDef> = {
  road: {
    id: 'road',
    name: 'Straße',
    cat: 'infra',
    cost: 4,
    unlockLv: 1,
    needsRoad: false,
    power: 0,
    water: 0,
    color: '#5c5c5c',
    icon: '═',
    blurb: 'Pflicht-Anbindung.',
  },
  highway: {
    id: 'highway',
    name: 'Schnellstraße',
    cat: 'infra',
    cost: 18,
    unlockLv: 5,
    needsRoad: false,
    power: 0,
    water: 0,
    color: '#3d3d3d',
    icon: '≣',
    blurb: 'Bessere Kapazität (zählt als Straße).',
  },
  house: {
    id: 'house',
    name: 'Wohnhaus',
    cat: 'house',
    cost: 40,
    unlockLv: 1,
    needsRoad: true,
    power: 1,
    water: 1,
    color: '#c9855a',
    icon: '⌂',
    blurb: 'Bevölkerung & Steuern.',
  },
  woodcutter: {
    id: 'woodcutter',
    name: 'Holzfäller',
    cat: 'raw',
    cost: 60,
    unlockLv: 1,
    needsRoad: true,
    power: 1,
    water: 0,
    produce: { out: 'wood', amount: 2, ms: 11_000 },
    color: '#2d6a4f',
    icon: '🌲',
    blurb: 'Rohstoff: Holz.',
  },
  mine: {
    id: 'mine',
    name: 'Bergwerk',
    cat: 'raw',
    cost: 110,
    unlockLv: 6,
    needsRoad: true,
    power: 2,
    water: 0,
    produce: { out: 'metal', amount: 2, ms: 16_000 },
    color: '#6c757d',
    icon: '⛏️',
    blurb: 'Rohstoff: Metall.',
  },
  chem: {
    id: 'chem',
    name: 'Chemie',
    cat: 'raw',
    cost: 140,
    unlockLv: 12,
    needsRoad: true,
    power: 2,
    water: 1,
    produce: { out: 'chemicals', amount: 2, ms: 18_000 },
    color: '#7b2cbf',
    icon: '🏭',
    blurb: 'Rohstoff: Chemikalien.',
  },
  plastics: {
    id: 'plastics',
    name: 'Kunststoffwerk',
    cat: 'raw',
    cost: 150,
    unlockLv: 14,
    needsRoad: true,
    power: 2,
    water: 1,
    produce: { out: 'plastic', amount: 2, ms: 17_000, in: { chemicals: 1 } },
    color: '#7209b7',
    icon: '🧴',
    blurb: '1 Chemikalie → Kunststoff.',
  },
  glassworks: {
    id: 'glassworks',
    name: 'Glashütte',
    cat: 'raw',
    cost: 150,
    unlockLv: 16,
    needsRoad: true,
    power: 2,
    water: 1,
    produce: { out: 'glass', amount: 2, ms: 20_000 },
    color: '#48cae4',
    icon: '🫙',
    blurb: 'Rohstoff: Glas.',
    region: 'coast',
  },
  sawmill: {
    id: 'sawmill',
    name: 'Schreinerei',
    cat: 'craft',
    cost: 90,
    unlockLv: 3,
    needsRoad: true,
    power: 1,
    water: 0,
    produce: { out: 'planks', amount: 1, ms: 15_000, in: { wood: 2 } },
    color: '#9c6644',
    icon: '🪚',
    blurb: '2 Holz → Bretter.',
  },
  workshop: {
    id: 'workshop',
    name: 'Werkstatt',
    cat: 'craft',
    cost: 160,
    unlockLv: 8,
    needsRoad: true,
    power: 2,
    water: 0,
    produce: { out: 'tools', amount: 1, ms: 22_000, in: { metal: 2, wood: 1 } },
    color: '#e76f51',
    icon: '🔩',
    blurb: 'Metall+Holz → Werkzeug.',
  },
  textile: {
    id: 'textile',
    name: 'Textilwerk',
    cat: 'craft',
    cost: 180,
    unlockLv: 18,
    needsRoad: true,
    power: 1,
    water: 1,
    produce: { out: 'fabric', amount: 2, ms: 24_000, in: { plastic: 1 } },
    color: '#f72585',
    icon: '🧵',
    blurb: 'Kunststoff → Stoffe.',
  },
  furniture: {
    id: 'furniture',
    name: 'Möbelfabrik',
    cat: 'craft',
    cost: 240,
    unlockLv: 20,
    needsRoad: true,
    power: 2,
    water: 1,
    produce: { out: 'furniture', amount: 1, ms: 30_000, in: { planks: 2, fabric: 1 } },
    color: '#9c6644',
    icon: '🛋️',
    blurb: 'Bretter+Stoffe → Möbel.',
  },
  power: {
    id: 'power',
    name: 'Kraftwerk',
    cat: 'util',
    cost: 120,
    unlockLv: 1,
    needsRoad: true,
    power: 0,
    water: 0,
    radius: 4,
    color: '#e9c46a',
    icon: '⚡',
    blurb: 'Fossile Energie.',
  },
  solar: {
    id: 'solar',
    name: 'Solarpark',
    cat: 'util',
    cost: 200,
    unlockLv: 22,
    needsRoad: true,
    power: 0,
    water: 0,
    radius: 5,
    color: '#ffd166',
    icon: '☀️',
    blurb: 'Erneuerbar, größerer Radius.',
    region: 'desert',
  },
  water: {
    id: 'water',
    name: 'Wasserturm',
    cat: 'util',
    cost: 100,
    unlockLv: 1,
    needsRoad: true,
    power: 0,
    water: 0,
    radius: 4,
    color: '#4cc9f0',
    icon: '💧',
    blurb: 'Wasserversorgung.',
  },
  sewage: {
    id: 'sewage',
    name: 'Kläranlage',
    cat: 'util',
    cost: 160,
    unlockLv: 10,
    needsRoad: true,
    power: 1,
    water: 0,
    radius: 4,
    color: '#457b9d',
    icon: '🚰',
    blurb: 'Abwasser — hält Zufriedenheit.',
  },
  waste: {
    id: 'waste',
    name: 'Mülldepot',
    cat: 'util',
    cost: 130,
    unlockLv: 11,
    needsRoad: true,
    power: 1,
    water: 0,
    radius: 4,
    color: '#6d6875',
    icon: '🗑️',
    blurb: 'Müllentsorgung.',
  },
  police: {
    id: 'police',
    name: 'Polizei',
    cat: 'civic',
    cost: 200,
    unlockLv: 25,
    needsRoad: true,
    power: 1,
    water: 1,
    radius: 5,
    color: '#1d3557',
    icon: '🚓',
    blurb: 'Sicherheitsradius.',
  },
  fire: {
    id: 'fire',
    name: 'Feuerwehr',
    cat: 'civic',
    cost: 200,
    unlockLv: 26,
    needsRoad: true,
    power: 1,
    water: 1,
    radius: 5,
    color: '#e63946',
    icon: '🚒',
    blurb: 'Brandschutz.',
  },
  hospital: {
    id: 'hospital',
    name: 'Krankenhaus',
    cat: 'civic',
    cost: 280,
    unlockLv: 28,
    needsRoad: true,
    power: 2,
    water: 2,
    radius: 6,
    color: '#f8f9fa',
    icon: '🏥',
    blurb: 'Gesundheit.',
  },
  park: {
    id: 'park',
    name: 'Park',
    cat: 'special',
    cost: 50,
    unlockLv: 2,
    needsRoad: true,
    power: 0,
    water: 0,
    radius: 2,
    color: '#52b788',
    icon: '🌳',
    blurb: 'Zufriedenheits-Booster.',
  },
  school: {
    id: 'school',
    name: 'Schule',
    cat: 'special',
    cost: 260,
    unlockLv: 30,
    needsRoad: true,
    power: 1,
    water: 1,
    radius: 5,
    color: '#f4a261',
    icon: '🏫',
    blurb: 'Bildung & Turm-Freischaltung.',
  },
  uni: {
    id: 'uni',
    name: 'Universität',
    cat: 'special',
    cost: 600,
    unlockLv: 48,
    needsRoad: true,
    power: 2,
    water: 2,
    radius: 7,
    color: '#e9c46a',
    icon: '🎓',
    blurb: 'Starker Steuerbonus.',
  },
  station: {
    id: 'station',
    name: 'Bahnhof',
    cat: 'special',
    cost: 350,
    unlockLv: 42,
    needsRoad: true,
    power: 2,
    water: 1,
    radius: 6,
    color: '#264653',
    icon: '🚉',
    blurb: 'Handelsrouten / Club-Krieg-Bonus.',
  },
  airport: {
    id: 'airport',
    name: 'Flughafen',
    cat: 'special',
    cost: 900,
    unlockLv: 65,
    needsRoad: true,
    power: 3,
    water: 2,
    radius: 8,
    color: '#457b9d',
    icon: '✈️',
    blurb: 'Globaler Handel-Bonus.',
  },
  cinema: {
    id: 'cinema',
    name: 'Kino',
    cat: 'special',
    cost: 220,
    unlockLv: 35,
    needsRoad: true,
    power: 2,
    water: 1,
    radius: 4,
    color: '#9b2226',
    icon: '🎬',
    blurb: 'Freizeit-Zufriedenheit.',
  },
  stadium: {
    id: 'stadium',
    name: 'Stadion',
    cat: 'special',
    cost: 700,
    unlockLv: 55,
    needsRoad: true,
    power: 3,
    water: 2,
    radius: 6,
    color: '#2a9d8f',
    icon: '🏟️',
    blurb: 'Sport & Einkommen.',
  },
  landmark: {
    id: 'landmark',
    name: 'Wahrzeichen',
    cat: 'special',
    cost: 1200,
    unlockLv: 75,
    needsRoad: true,
    power: 3,
    water: 2,
    color: '#cdb4db',
    icon: '🗽',
    blurb: '+8% globale Zufriedenheit.',
  },
  depot: {
    id: 'depot',
    name: 'Handelsdepot',
    cat: 'special',
    cost: 300,
    unlockLv: 38,
    needsRoad: true,
    power: 1,
    water: 1,
    color: '#bc6c25',
    icon: '🏪',
    blurb: 'Mehr Spieler-Angebote am Markt.',
  },
};

export const BUILD_ORDER: BuildId[] = [
  'road',
  'highway',
  'house',
  'woodcutter',
  'sawmill',
  'mine',
  'workshop',
  'chem',
  'plastics',
  'glassworks',
  'textile',
  'furniture',
  'power',
  'solar',
  'water',
  'sewage',
  'waste',
  'police',
  'fire',
  'hospital',
  'park',
  'school',
  'uni',
  'cinema',
  'stadium',
  'station',
  'airport',
  'depot',
  'landmark',
];

export function emptyInv(): Record<Res, number> {
  return {
    wood: 0,
    metal: 0,
    plastic: 0,
    glass: 0,
    chemicals: 0,
    planks: 0,
    tools: 0,
    furniture: 0,
    fabric: 0,
  };
}
